openapi: 3.0.0
info:
  title: Package Delivery API
  description: API for managing package delivery items
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
paths:
  /packageitems:
    post:
      summary: Create a new package item
      tags:
        - PackageItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageItem'
      responses:
        '201':
          description: Package item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageItemResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
    get:
      summary: Get all package items
      tags:
        - PackageItems
      responses:
        '200':
          description: A list of package items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageItemResponse'
        '500':
          description: Server error
  /packageitems/{id}:
    get:
      summary: Get a package item by ID
      tags:
        - PackageItems
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Package item found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageItemResponse'
        '404':
          description: Package item not found
        '500':
          description: Server error
    put:
      summary: Update a package item
      tags:
        - PackageItems
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageItem'
      responses:
        '200':
          description: Package item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageItemResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Package item not found
        '500':
          description: Server error
  /packageitems/user/{email}:
    get:
      summary: Get package items by user email
      tags:
        - PackageItems
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of package items for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageItemResponse'
        '404':
          description: User not found
        '500':
          description: Server error
  /packageitems/search:
    get:
      summary: Search package items
      tags:
        - PackageItems
      responses:
        '200':
          description: A list of package items matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageItemResponse'
        '500':
          description: Server error
components:
  schemas:
    PackageItem:
      type: object
      properties:
        packageName:
          type: string
        priority:
          type: string
        description:
          type: string
        currentStatus:
          type: string
        additionalInstructions:
          type: string
        deliveryDetails:
          type: object
          properties:
            deliveryDate:
              type: string
              format: date
            deliveryTime:
              type: string
              format: time
            assignedDriver:
              type: string
            trackingNumber:
              type: string
    PackageItemResponse:
      allOf:
        - $ref: '#/components/schemas/PackageItem'
        - type: object
          properties:
            id:
              type: string